version: "3.8" 
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
        - "5672:5672"
        - "15672:15672" 
  producer:
    container_name: server-producer
    image: server-producer
    build: ./ServerProducer/
    restart: on-failure
    ports:
        - "8080:8080"
    environment:
        - spring_rabbitmq_host=rabbitmq
        - spring_rabbitmq_port=5672
        - spring_rabbitmq_username=guest
        - spring_rabbitmq_password=guest
    depends_on:
        - rabbitmq 
  consumer:
    container_name: server-consumer
    image: server-consumer
    build: ./ServerConsumer/
    restart: on-failure
    ports:
        - "8081:8081"
    environment:
        - spring_rabbitmq_host=rabbitmq
        - spring_rabbitmq_port=5672
        - spring_rabbitmq_username=guest
        - spring_rabbitmq_password=guest
    depends_on:
        - producer 
  ta9client:
    container_name: ta9client
    image: ta9client
    build: ./Ta9Client/
    ports:
        - "80:80"
      